site_name: OneCode Library

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/oc_light.png
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.expand

nav:
  - Getting Started: index.md
  - OneCode Cloud: user_doc.md
  - Python Cheatsheet:
     - Elements: reference/elements/element_list.md
     - Organizing data: organizing_data.md
  - Full API:
    - CLI: reference/cli/cli.md
    - Elements:
      - Input Elements: reference/elements/input_elements_api.md
      - Output Elements: reference/elements/output_elements_api.md
    - Base:
      - Logger: reference/base/logger.md
      - Enumerator: reference/base/enums.md
      - Project: reference/base/project.md
  - FAQs: faq.md
  - Changelogs:
    - 1.0.0: changelogs/1.0.0.md
    - 0.4.0: changelogs/0.4.0.md
    - 0.3.0: changelogs/0.3.0.md
    - 0.2.1: changelogs/0.2.1.md
    - 0.2.0: changelogs/0.2.0.md
    - 0.1.0: changelogs/0.1.0.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: True
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_root_toc_entry: false
            separate_signature: false
            new_path_syntax: yes
            filters:
              - "^_"
              - "^"
  - autorefs


extra_css:
        - stylesheets/extra.css

extra:
  homepage: https://deeplime.io/
  version:
    provider: mike

copyright: Copyright &copy; 2022 - 2024, DeepLime
