site_name: OneCode Library

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/oc_light.png
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.expand

nav:
  - Getting Started: index.md
  - Tips and Tricks: tips_and_tricks.md
  - API Reference:
    - CLI: reference/cli/cli.md
    - Base:
      - Logger: reference/base/logger.md
      - Enumerator: reference/base/enums.md
      - Project: reference/base/project.md
    - Elements:
      - Input Elements: reference/elements/input_element_list.md
      - Output Elements: reference/elements/output_element_list.md
  - Developer's corner:
    - CLI:
      - Create a project: reference/cli/create.md
      - Add a flow to a project: reference/cli/add.md
      - Run a project in UI mode: reference/cli/start.md
      - Extract project parameters: reference/cli/extract.md
      - Utilities: reference/cli/utils.md
    - InputElements:
      - Abstract InputElement: reference/elements/input_element.md
      - Checkbox: reference/elements/input/checkbox.md
      - RadioButton: reference/elements/input/radio_button.md
      - Dropdown: reference/elements/input/dropdown.md
      - NumberInput: reference/elements/input/number_input.md
      - Slider: reference/elements/input/slider.md
      - FileInput: reference/elements/input/file_input.md
      - FolderInput: reference/elements/input/folder_input.md
      - TextInput: reference/elements/input/text_input.md
      - CsvReader: reference/elements/input/csv_reader.md
    - OutputElement:
      - Abstract OutputElement: reference/elements/output_element.md
      - FileOutput: reference/elements/output/file_output.md
    - Utilities: reference/utils/utils.md
    - Extending OneCode: extending_onecode.md
  - Changelogs:
    - 1.0.0: changelogs/1.0.0.md
    - 0.4.0: changelogs/0.4.0.md
    - 0.3.0: changelogs/0.3.0.md
    - 0.2.1: changelogs/0.2.1.md
    - 0.2.0: changelogs/0.2.0.md
    - 0.1.0: changelogs/0.1.0.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: True
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_root_toc_entry: false
            separate_signature: false
            new_path_syntax: yes
            filters:
              - "^_"
              - "^"
  - autorefs


extra_css:
        - stylesheets/extra.css

extra:
  homepage: https://deeplime.io/
  version:
    provider: mike

copyright: Copyright &copy; 2022 - 2024, DeepLime
