name: Bug Report
description: Report a problem
title: ""
labels: ["bug", "new"]

body:

  - type: markdown
    attributes:
      value: |
        ## Your Environment
  - type: input
    id: version
    attributes:
      label: Version (tag/commit sha)
      description: Which Version of OneCode are you on.
      placeholder: ex. 0.1.0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      description: Which OS are you on ?
      multiple: false
      options:
        - Linux
        - Windows
    validations:
      required: true
  - type: checkbox
    id: profile
    attributes:
      label: Profile
      description: What is your OneCode profile ?
      options:
        - Expert
        - Tech-Savvy
        - Developer
    validations:
      required: false
  - type: textarea
    id: problem-description
    attributes:
      label: Problem description
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened ?
      placeholder: |
        * Code snippet
        ```python
        # sample code here
        ```

        * Screenshot/Output of the bug
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: What should have happened
      placeholder: ex. one elemenent did not render as I expected.
    validations:
      required: true


