name: New Feature/Enhancement request
description: Request a new feature or an improvement to an existing one
title: "[Request]: "
labels: ["change request", "new"]

body:

  - type: markdown
    attributes:
      value: |
        ## Change request type
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: New feature or Improvement?
      multiple: false
      options:
        - New feature
        - Improvement
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Product
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: OneCode Cloud or OneCode Python?
      multiple: false
      options:
        - OneCode Cloud
        - OneCode Python
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details
      placeholder: |
        * Description

        * Sample Code (for OneCode Python)
        ```python
        # example of code that would illustrate this request

        ```
    validations:
      required: true
