name: New Feature/Enhancement request
description: Request a new feature or an improvement to an existing one
title: "[Request]: "
labels: ["change request", "new"]

body:

  - type: markdown
    attributes:
      value: |
        ## Change request type
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: New feature or Improvement ?
      multiple: false
      options:
        - New feature
        - Improvement
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      description: Is it OS-specific ?
      multiple: false
      options:
        - Not particularly
        - Linux
        - Windows
    validations:
      required: true
  - type: checkboxes
    id: profile
    attributes:
      label: Profile
      description: Who is it for ?
      options:
        - label: Expert
        - label: Tech-Savvy
        - label: Developer
    validations:
      required: false
  - type: textarea
    id: details
    attributes:
      label: Details
      placeholder: |
        * Description

        * Sample Code
        ```python
        # example of code that would illustrate this request
        ```

        * Desired screenshot/output
    validations:
      required: true
