name: Question
description: Ask a question
title: "[Question]: "
labels: ["question", "new"]

body:

  - type: checkboxes
    id: answer
    attributes:
      label: Answer
      description: To the best of my knowledge, I didn't find a complete answer in
      options:
        - label: the [documentation](https://deeplime-io.github.io/onecode)
        - label: the GitHub Issues
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Product
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: OneCode Cloud or OneCode Python?
      multiple: false
      options:
        - OneCode Cloud
        - OneCode Python
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version (tag/commit sha)
      description: '[Python only] Which Version of OneCode are you on?'
      placeholder: ex. 0.1.0
    validations:
      required: false
      
  - type: textarea
    id: question
    attributes:
      label: Question
      placeholder: Your question
    validations:
      required: true
