name: Question
description: Ask a question
title: ""
labels: ["question", "new"]

body:
  - type: checkbox
    id: answer
    attributes:
      label: Answer
      description: To the best of my knowledge, I didn't find a complete answer in
      options:
        - the [documentation](https://deeplime-io.github.io/onecode)
        - the GitHub Issues
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Your Environnement
  - type: input
    id: version
    attributes:
      label: Version (tag/commit sha)
      description: Which Version of OneCode are you on.
      placeholder: ex. 0.1.0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      description: Which OS are you on ?
      multiple: false
      options:
        - Linux
        - Windows
    validations:
      required: true
  - type: checkbox
    id: profile
    attributes:
      label: Profile
      description: What is your OneCode profile ?
      options:
        - Expert
        - Tech-Savvy
        - Developer
    validations:
      required: false
  - type: textarea
    id: question
    attributes:
      label: Question
      placeholder: Your question
    validations:
      required: true