name: Changelog Check

on:
  pull_request:
    branches:
      - '*.x'

jobs:
  check:
    name: Check Changelog
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python libraries
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Check changelog update
      run: |
        BRANCH_SHA1=`sha1sum ./docs/changelogs/*.md || echo 'NULL'`

        git checkout ${{ github.event.pull_request.base.sha }}
        MAIN_SHA1=`sha1sum ./docs/changelogs/*.md || echo 'NULL'`

        if [ "$BRANCH_SHA1" == "$MAIN_SHA1" ]
        then
          echo "Missing changelog information"
          exit 1
        else
          echo "Changelog OK"
        fi
